### ISSUE TITLE
Support Request [ASUS B550-F GAMING]

### ISSUE THREAD

**Issue by Kydaix** [justinlin099/UWSP-Universal-Windows-7-Project#1]
Hello !

I don't know if we have the ability to request the addition of news, so I'm trying.
I wanted to know if there was a possibility to add a better support for the Asus B550-F Gaming.

Thank you.

**Comment by justinlin099** [comment]
What support do you need?
Please describe detailed information
Thanks you.

**Comment by Kydaix** [comment]
Sorry for the inconvenience, but I managed to install it! 😄
However, I still have things to ask...

First of all, I can just inform that it works on an Asus B550-F GAMING, so if you want you can add it to the motherboard list.

But I still have a question! Currently I'm trying to install a custom Windows 7 (other than this one), but it's not compatible with the B550 chipset, so I wanted to know what drivers you used (if you're okay), so I can integrate them using NTLite.

Anyway, thanks for your answer!
Keep up the good work, and if you need testers for some stuff with a B550-F Gaming, I'm there!

Edit: in fact, I already tried using NTLite to integrate missing drivers to the custom W7, both windows and boot image, however, I can install it, but once it finished the setup and tried booting again, it freezes on the boot animation, then if I try to boot in SafeMode, it's stuck loading "classpnp.sys".

**Comment by justinlin099** [comment]
The driver other than usb drivers are probably fine
You can download it from AMD's official website by downloading the X470
one's.
But for the USB Driver It's more complicated

Kydaix ***@***.***> 於 2022年5月9日 週一 上午3:15寫道：

**Comment by Kydaix** [comment]
Hi!

Thanks for your answer! In fact, I found USB drivers that work, as well as this for the display.
Then after tests, I discovered the cause of my problem but I can't find a solution!
But my problem is with the Storage Controller, I get a blue-screen with the error "0x0000007B".
So I wanted to know what are your Storage Controller drivers to avoid this problem? Do you have a link?

Thanks!

**Comment by justinlin099** [comment]
Is it always blue screen?
Or just sometimes it happens?
I think I just use nvme driver for Windows 7

**Comment by Kydaix** [comment]
Well, to be precise:
- I boot on USB to install Windows 7.
- Then, I launch the installation (after having made my partitions, etc...), everything is fine.
- Windows installs itself and says that the installation will continue after a reboot.
- The computer restarts, and continues the installation. Then it says again that it has to reboot again to complete the installation.
- The computer restarts and freezes during the Windows 7 startup animation ("Starting Windows").

That's exactly what it does to me. Then if I force the PC to shut down and restart it, I have two options that always happens:
- If I run in SafeMode, it freezes when loading "classpnp.sys".
- If I launch it by "choosing the last settings that worked", it starts then blue-screen with the error "0x0000007B".

And I don't have NVME, but what I don't understand is that everything is fine with your Windows 7, but not the one I want to install even if I integrate drivers, and also why I can access the setup, but once it is installed it does not work... :(

**Comment by justinlin099** [comment]
As I remember,If you integrate the official driver from amd website
make sure you delete all the windows 10 driver and only install win7 x64
one's or otherwise it'll BSOD

Kydaix ***@***.***> 於 2022年5月10日 週二 上午2:14寫道：

**Comment by justinlin099** [comment]
By the way, I was curious to ask what's special about that custom Windows 7 build.
I'd like to know the reason you want to use that and I'll look into it.

**Comment by Kydaix** [comment]
Well, unfortunately even after trying this option, it doesn't work. I think I don't have the knowledge about drivers to do it... :(

It is a modified version of W7 called [FoxOS](https://discord.gg/y6tYP6Z), created by CatGamerOP.
It aims to be better for gaming, and includes many optimizations and is extremly tweaked, it is better mainly for latency.

Currently, I use [ggOS](https://discord.gg/ggos), created by Phlegm, which is a Windows 10 having about the same objective as FoxOS but in less advanced. But I customized it with NTLite to push it a bit more so that without any program running, I only consume 700 MB of RAM.
But I'm mostly the kind of person who prefers low latency, and I know that FoxOS is generally better for that. That's why I would like to install it.
